disabled_rules:
- trailing_whitespace
- colon
- force_cast
- unused_closure_parameter
- vertical_whitespace
- comma
- trailing_newline
- closure_parameter_position
- opening_brace
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 550
    error: 600
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 400
    error: 600
function_parameter_count:
    warning: 20
    error: 25
type_body_length:
    warning: 400
    error: 600
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
